language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
#sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/BlynkClient PLATFORMIO_CI_ARGS="--board=leonardo"
    - PLATFORMIO_CI_SRC=examples/FileDownload PLATFORMIO_CI_ARGS="--board=leonardo"
    - PLATFORMIO_CI_SRC=examples/MqttClient PLATFORMIO_CI_ARGS="--board=leonardo"
    - PLATFORMIO_CI_SRC=examples/WebClient PLATFORMIO_CI_ARGS="--board=leonardo"
    - PLATFORMIO_CI_SRC=tools/SimpleTest PLATFORMIO_CI_ARGS="--board=leonardo"
    - PLATFORMIO_CI_SRC=tools/FactoryReset PLATFORMIO_CI_ARGS="--board=leonardo"
    - PLATFORMIO_CI_SRC=tools/AT_Debug PLATFORMIO_CI_ARGS="--board=leonardo"

    # Arduino test
    - PLATFORMIO_CI_SRC=extras/test_build PLATFORMIO_CI_ARGS="--board=uno --board=leonardo --board=yun --board=megaatmega2560 --board=genuino101 --board=mkr1000USB --board=zero --board=teensy31 --board=uno_pic32 --board=esp01 --board=nodemcuv2 --board=esp32dev"
    - PLATFORMIO_CI_SRC=extras/test_build PLATFORMIO_CI_ARGS='--board=bluepill_f103c8 --project-option="framework=arduino"'

    # Energia test
    - PLATFORMIO_CI_SRC=extras/test_build PLATFORMIO_CI_ARGS='--board=lplm4f120h5qr --project-option="framework=energia"'

install:
    # ChipKIT issue: install 32-bit support for GCC PIC32
    - sudo apt-get install libc6-i386

    - pip install -U https://github.com/platformio/platformio/archive/develop.zip

    #
    # Libraries from PlatformIO Library Registry:
    #
    # http://platformio.org/lib/show/89/PubSubClient
    # http://platformio.org/lib/show/415/Blynk
    # http://platformio.org/lib/show/1202/CRC32
    # http://platformio.org/lib/show/1286/StreamDebugger

    - platformio lib -g install 89 415 1202 1286

script:
    - platformio ci --lib="." $PLATFORMIO_CI_ARGS
